#!/bin/bash
# Exit immediately if a command exits with a non-zero status.
set -e

# --- Configuration ---
# Define inventory paths for clarity
LOCAL_INVENTORY="ansible/inventory/local.ini"
PROD_INVENTORY="ansible/inventory/production.ini"
PLAYBOOK="ansible/playbooks/playbook.yml"
ANSIBLE_ROLES_DIR="ansible/roles" # Define roles path for local run

echo "INFO: Deployment script started."

# --- STAGE 1: LOCAL VALIDATION ---
echo "--------------------------------------------------"
echo "STAGE 1: Running Ansible playbook locally for validation..."
echo "--------------------------------------------------"

# Install Ansible dependencies first
ansible-galaxy install -r ansible/requirements.yml

# Execute the playbook against the localhost runner.
# We use --syntax-check for a quick validation. For a full test, remove it.
# A full run would install Docker/Nginx on the runner, which is a very thorough test.
ansible-playbook -i "$LOCAL_INVENTORY" "$PLAYBOOK" --syntax-check

# For a more complete test, you can run the full playbook.
# This will actually try to install Docker, Nginx etc. on the CI runner.
# It's a great way to find errors. Uncomment the line below to enable it.
# ansible-playbook -i "$LOCAL_INVENTORY" "$PLAYBOOK" --extra-vars "ansible_roles_path=$ANSIBLE_ROLES_DIR"

echo "SUCCESS: Local Ansible validation passed."


# --- STAGE 2: PROVISION INFRASTRUCTURE ---
echo "--------------------------------------------------"
echo "STAGE 2: Provisioning infrastructure with Terraform..."
echo "--------------------------------------------------"

cd terraform/
terraform init -input=false
terraform apply -auto-approve -input=false
cd ..

echo "SUCCESS: Terraform has provisioned the infrastructure."
echo "INFO: The production inventory file at '$PROD_INVENTORY' has been automatically updated."


# --- STAGE 3: DEPLOY TO PRODUCTION ---
echo "--------------------------------------------------"
echo "STAGE 3: Running Ansible playbook on the production server..."
echo "--------------------------------------------------"

# Disable host key checking for the first connection to the new server
export ANSIBLE_HOST_KEY_CHECKING=False

# Run the same playbook, but this time using the production inventory
# that was generated by Terraform.
ansible-playbook -i "$PROD_INVENTORY" "$PLAYBOOK"

echo "--------------------------------------------------"
echo "DEPLOYMENT COMPLETE: The server is fully configured."
echo "--------------------------------------------------"
