services:
  gitea:
    image: gitea/gitea:1.21.11
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3000:3000"

  # my portfolio
  resume:
    build:
      context: https://github.com/snjy5/resume.git
    ports:
      - "127.0.0.1:8090:80"
    restart: unless-stopped

# Define a custom network so containers can talk to each other securely
networks:
  default:
    name: infrastructure_net
