#
# This file is automatically edited by Terraform.
# Do not edit this file manually, as your changes will be overwritten.
#

[webservers]
prod_server ansible_host=${host_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${ssh_key_path}
