# ansible/inventory/local.ini
[webservers]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[webservers:vars]
skip_ssl_provisioning=true
main_domain=ci-test.local
vault_admin_email=admin@ci-test.local
