#!/usr/bin/python3
import sys

if len(sys.argv) < 2:
    print("Usage: python3 add_peer <peer_name>")
    sys.exit(1)

peer_name = sys.argv[1]

peer_block = f"""

[Peer] 
# {peer_name}
PublicKey = {peer_name}_public_keystring
Endpoint = 10.0.1.0:9128 # wg iface ip & forwarded port
AllowedIPs = 10.0.0.1/32, 10.0.0.2/32 # client ips to whitelist

"""

with open("wg0.conf", "a") as f:
    f.write(peer_block)

print(f"Successfully added {peer_name} to wg0.conf!")
