[Interface]
PrivateKey = private_keystring
ListenPort = 51820 # wg uses for runtime
Address = 10.0.1.0/24 # wg interface on host

[Peer] 
# new
PublicKey = new_public_keystring
Endpoint = 10.0.1.0:9128 # wg iface ip & forwarded port
AllowedIPs = 10.0.0.1/32, 10.0.0.2/32 # client ips to whitelist

