---
- name: Configure Server and Deploy Applications
  hosts: webservers
  become: true

  # Standard vars are now auto-loaded from group_vars/webservers.yml
  vars_files:
    - ../inventory/group_vars/all/vault.yml

  roles:
    - role: common
    - role: geerlingguy.firewall
    - role: geerlingguy.security
    - role: geerlingguy.docker
    - role: nginx
    - role: app_deploy
