- hosts: nms
  become: yes
  vars:
    nginx_license:
      certificate: ./nginx-repo.crt
      key: ./nginx-repo.key
    nms_setup: install
    nms_version: 2.16.0*
    nms_user_name: admin
    nms_user_passwd: default
    nms_modules:
      - name: sm
  collections:
    - nginxinc.nginx_core
  roles:
    - nginxinc.nginx_management_suite