# ansible/inventory/group_vars/webservers.yml

# geerlingguy.security - SSH hardening
security_ssh_permit_root_login: "no"
security_ssh_password_authentication: "no"
security_ssh_x11_forwarding: "no"
security_ssh_max_auth_trries: 3
security_fail2ban_enabled: true
security_autoupdate_enabled: true
security_autoupdate_reboot: false

# geerlingguy.docker
docker_install_compose_plugin: true

# geerlingguy.firewall
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
firewall_allowed_udp_ports:
  - "51820"
firewall_state: "started"
firewall_default_deny_incoming: true

# Custom App Variables
app_base_dir: /opt/app
resume_repo_url: https://github.com/snjy5/resume.git
resume_repo_branch: master

# Nginx / SSL Role Variables
admin_email: "{{ vault_admin_email }}"
webroot_path: "/var/www/certbot"
cert_min_days: 30

# gitea install setup
gitea_admin_username: "{{ vault_gitea_admin_username }}"
gitea_admin_password: "{{ vault_gitea_admin_password }}"
gitea_admin_email: "{{ vault_admin_email }}"

# Application config (used by reverse-proxy.conf.j2 template)
main_domain: "{{ vault_main_domain }}"
services:
  - name: gitea
    port: 3000
  - name: resume
    port: 8090
