name: main

on:
  push:
    branches: [ "master" ]

env:
  INVENTORY: ansible/inventory/inventory.yml
  NGINX_DIR: ansible/roles/nginx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python  
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Install Galaxy Requirements
      run: ansible-galaxy install -fr ${{ env.NGINX_DIR }}/requirements.yml

    - name: Test Inventory Connectivity
      run: ansible all -i ${{ env.INVENTORY }} -m ping
      
    - name: Run Main Playbook
      run: ansible-playbook -i ${{ env.INVENTORY }} ansible/playbooks/playbook.yml

    - name: Verify Nginx is running
      run: curl --fail http://localhost:8080
